simple:
  model: "mistralai/mistral-large-2411"
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 4000

simple_json:
  model: "qwen/qwen-plus"
  temperature: 0.7
  top_p: 1.0
  n: 1
  max_tokens: 4000
  json: true

agent:
  model: "meta-llama/llama-3.3-70b-instruct"
  temperature: 0.8
  top_p: 0.95
  n: 1
  max_tokens: 4000

generator:
  model: "mistralai/mistral-nemo"
  temperature: 0.7
  top_p: 0.9
  n: 1
  max_tokens: 8000
  repetition_penalty: 1.0

refiner:
  model: "mistralai/mistral-nemo"
  temperature: 0.7
  top_p: 0.9
  n: 1
  max_tokens: 8000
  repetition_penalty: 1.0

adviser:
  model: "mistralai/mistral-nemo"
  temperature: 0.7
  top_p: 0.9
  n: 1
  max_tokens: 4000

reflector:
  model: "mistralai/mistral-nemo"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 4000

searcher:
  model: "mistralai/mistral-nemo"
  temperature: 0.8
  top_p: 0.95
  n: 1
  max_tokens: 4000

enricher:
  model: "mistralai/mistral-nemo"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 4000

coder:
  model: "mistralai/mistral-nemo"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 6000

installer:
  model: "mistralai/mistral-nemo"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 4000

pentester:
  model: "mistralai/mistral-nemo"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 4000
