simple:
  model: "meta-llama/Llama-3.3-70B-Instruct"
  temperature: 0.6
  top_p: 0.95
  n: 1
  max_tokens: 4000
  price:
    input: 0.038
    output: 0.12

simple_json:
  model: "google/gemma-3-27b-it"
  temperature: 0.7
  top_p: 1.0
  n: 1
  max_tokens: 4000
  json: true
  price:
    input: 0.09
    output: 0.17

primary_agent:
  model: "deepseek-ai/DeepSeek-R1-0528-Turbo"
  n: 1
  max_tokens: 6000
  price:
    input: 1.0
    output: 3.0

assistant:
  model: "deepseek-ai/DeepSeek-R1-0528-Turbo"
  n: 1
  max_tokens: 8000
  price:
    input: 1.0
    output: 3.0

generator:
  model: "deepseek-ai/DeepSeek-R1-0528-Turbo"
  n: 1
  max_tokens: 12000
  price:
    input: 1.0
    output: 3.0

refiner:
  model: "deepseek-ai/DeepSeek-R1-0528-Turbo"
  n: 1
  max_tokens: 8000
  price:
    input: 1.0
    output: 3.0

adviser:
  model: "google/gemini-2.5-pro"
  n: 1
  max_tokens: 4000
  price:
    input: 0.875
    output: 7.0

reflector:
  model: "google/gemini-2.5-flash"
  n: 1
  max_tokens: 4000
  price:
    input: 0.21
    output: 1.75

searcher:
  model: "Qwen/Qwen3-32B"
  n: 1
  max_tokens: 4000
  price:
    input: 0.1
    output: 0.3

enricher:
  model: "Qwen/Qwen3-32B"
  n: 1
  max_tokens: 6000
  price:
    input: 0.1
    output: 0.3

coder:
  model: "anthropic/claude-4-sonnet"
  n: 1
  max_tokens: 8000
  price:
    input: 3.3
    output: 16.5

installer:
  model: "google/gemini-2.5-flash"
  n: 1
  max_tokens: 6000
  price:
    input: 0.21
    output: 1.75

pentester:
  model: "moonshotai/Kimi-K2-Instruct"
  n: 1
  max_tokens: 6000
  price:
    input: 0.55
    output: 2.2
