simple:
  model: "deepseek-chat"
  temperature: 0.6
  top_p: 0.95
  n: 1
  max_tokens: 4000

simple_json:
  model: "deepseek-chat"
  temperature: 0.7
  top_p: 1.0
  n: 1
  max_tokens: 4000
  json: true

agent:
  model: "deepseek-chat"
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 4000

generator:
  model: "deepseek-chat"
  temperature: 1.1
  top_p: 0.95
  n: 1
  max_tokens: 8000

refiner:
  model: "deepseek-chat"
  temperature: 0.8
  top_p: 0.95
  n: 1
  max_tokens: 8000

adviser:
  model: "deepseek-chat"
  temperature: 1.2
  top_p: 0.95
  n: 1
  max_tokens: 4000

reflector:
  model: "deepseek-reasoner"
  temperature: 1.0
  top_p: 1.0
  n: 1
  max_tokens: 4000

searcher:
  model: "deepseek-chat"
  temperature: 1.0
  top_p: 0.95
  n: 1
  max_tokens: 4000

enricher:
  model: "deepseek-chat"
  temperature: 0.95
  top_p: 1.0
  n: 1
  max_tokens: 6000

coder:
  model: "deepseek-coder"
  temperature: 0.7
  top_p: 1.0
  n: 1
  max_tokens: 6000

installer:
  model: "deepseek-coder"
  temperature: 1.2
  top_p: 1.0
  n: 1
  max_tokens: 4000

pentester:
  model: "deepseek-chat"
  temperature: 0.8
  top_p: 0.9
  n: 1
  max_tokens: 4000
