simple:
  model: "openai/gpt-4o"
  temperature: 0.6
  top_p: 0.95
  n: 1
  max_tokens: 4000

simple_json:
  model: "openai/gpt-4o-mini"
  temperature: 0.7
  top_p: 1.0
  n: 1
  max_tokens: 4000
  json: true

agent:
  model: "openai/gpt-4o"
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 4000

generator:
  model: "anthropic/claude-3.7-sonnet:thinking"
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 8000

refiner:
  model: "anthropic/claude-3.7-sonnet:thinking"
  temperature: 0.55
  top_p: 0.95
  n: 1
  max_tokens: 8000

adviser:
  model: "anthropic/claude-3.7-sonnet:thinking"
  temperature: 0.8
  top_p: 0.95
  n: 1
  max_tokens: 4000

reflector:
  model: "mistralai/mistral-large-2411"
  temperature: 0.8
  top_p: 1.0
  n: 1
  max_tokens: 4000

searcher:
  model: "openai/gpt-4o-mini"
  temperature: 0.7
  top_p: 0.95
  n: 1
  max_tokens: 4000

enricher:
  model: "openai/gpt-4o"
  temperature: 0.95
  top_p: 1.0
  n: 1
  max_tokens: 6000

coder:
  model: "anthropic/claude-3.7-sonnet"
  temperature: 0.9
  top_p: 1.0
  n: 1
  max_tokens: 6000

installer:
  model: "openai/gpt-4o"
  temperature: 0.8
  top_p: 1.0
  n: 1
  max_tokens: 4000

pentester:
  model: "anthropic/claude-3.7-sonnet"
  temperature: 0.65
  top_p: 0.9
  n: 1
  max_tokens: 4000
